[package]
name = "mofa-personal-news"
version.workspace = true
edition.workspace = true

[dependencies]
makepad-widgets.workspace = true
mofa-widgets = { path = "../../mofa-widgets" }
log.workspace = true
serde_json.workspace = true
dirs.workspace = true
